[workspace]
resolver = "2"
members = [
    "crates/rust-daq",
    "crates/rust-daq/pvcam-sys",
    "crates/daq-core",
    # "crates/daq-bin",
    # "crates/daq-examples",
]
exclude = [
    "crates/rust-daq/python",
    "crates/rust-daq/fuzz",
    "crates/daq-bin",
    "crates/daq-examples",
]
